// Web/Js/datos.js

const pokedexData = {
    1: {
        nombres: [
            "Bulbasaur", "Ivysaur", "Venusaur", "Charmander", "Charmeleon", "Charizard", 
            "Squirtle", "Wartortle", "Blastoise", "Caterpie", "Metapod", "Butterfree", 
            "Weedle", "Kakuna", "Beedrill", "Pidgey", "Pidgeotto", "Pidgeot", "Rattata", 
            "Raticate", "Spearow", "Fearow", "Ekans", "Arbok", "Pikachu", "Raichu", "Sandshrew", 
            "Sandslash", "Nidoran H.", "Nidorina", "Nidoqueen", "Nidoran M.", 
            "Nidorino", "Nidoking", "Clefairy", "Clefable", "Vulpix", "Ninetales", 
            "Jigglypuff", "Wigglytuff", "Zubat", "Golbat", "Oddish", "Gloom", 
            "Vileplume", "Paras", "Parasect", "Venonat", "Venomoth", "Diglett", 
            "Dugtrio", "Meowth", "Persian", "Psyduck", "Golduck", "Mankey", "Primeape", "Growlithe", 
            "Arcanine", "Poliwag", "Poliwhirl", "Poliwrath", "Abra", "Kadabra", 
            "Alakazam", "Machop", "Machoke", "Machamp", "Bellsprout", "Weepinbell", "Victreebel", 
            "Tentacool", "Tentacruel", "Geodude", "Graveler", "Golem", 
            "Ponyta", "Rapidash", "Slowpoke", "Slowbro", "Magnemite", "Magneton", 
            "Farfetch’d", "Doduo", "Dodrio", "Seel", "Dewgong", "Grimer", 
            "Muk", "Shellder", "Cloyster", "Gastly", "Haunter", 
            "Gengar", "Onix", "Drowzee", "Hypno", "Krabby", "Kingler", "Voltorb", 
            "Electrode", "Exeggcute", "Exeggutor", "Cubone", "Marowak", 
            "Hitmonlee", "Hitmonchan", "Lickitung", "Koffing", "Weezing", 
            "Rhyhorn", "Rhydon", "Chansey", "Tangela", "Kangaskhan", "Horsea", "Seadra", 
            "Goldeen", "Seaking", "Staryu", "Starmie", "Mr. Mime", "Scyther", "Jynx", 
            "Electabuzz", "Magmar", "Pinsir", "Tauros", "Magikarp", "Gyarados", "Lapras", 
            "Ditto", "Eevee", "Vaporeon", "Jolteon", "Flareon", "Porygon", "Omanyte", "Omastar", "Kabuto", 
            "Kabutops", "Aerodactyl", "Snorlax", "Articuno", "Zapdos", 
            "Moltres", "Dratini", "Dragonair", "Dragonite", "Mewtwo", "Mew"
        ],
        tipos: [
            "Planta/Veneno", "Planta/Veneno", "Planta/Veneno", "Fuego", "Fuego", "Fuego/Volador",
            "Agua", "Agua", "Agua", "Bicho", "Bicho", "Bicho/Volador", "Bicho/Veneno",
            "Bicho/Veneno", "Bicho/Veneno", "Normal/Volador", "Normal/Volador", "Normal/Volador",
            "Normal", "Normal", "Normal/Volador", "Normal/Volador", "Veneno", "Veneno",
            "Electrico", "Electrico", "Tierra", "Tierra", "Veneno", "Veneno", "Veneno/Tierra",
            "Veneno", "Veneno", "Veneno/Tierra", "Hada", "Hada", "Fuego", "Fuego", "Normal/Hada",
            "Normal/Hada", "Veneno/Volador", "Veneno/Volador", "Planta/Veneno", "Planta/Veneno",
            "Planta/Veneno", "Bicho/Planta", "Bicho/Planta", "Bicho/Veneno", "Bicho/Veneno",
            "Tierra", "Tierra", "Normal", "Normal", "Agua", "Agua", "Lucha", "Lucha", "Fuego", 
            "Fuego", "Agua", "Agua", "Agua/Lucha", "Psiquico", "Psiquico", "Psiquico", "Lucha",
            "Lucha", "Lucha", "Planta/Veneno", "Planta/Veneno", "Planta/Veneno", "Agua/Veneno", 
            "Agua/Veneno", "Roca/Tierra", "Roca/Tierra", "Roca/Tierra", "Fuego", "Fuego", "Agua/Psiquico",
            "Agua/Psiquico", "Electrico/Acero", "Electrico/Acero", "Normal/Volador", "Normal/Volador",
            "Normal/Volador", "Agua", "Agua/Hielo", "Veneno", "Veneno", "Agua", "Agua/Hielo", "Fantasma/Veneno",
            "Fantasma/Veneno", "Fantasma/Veneno", "Roca/Tierra", "Psiquico", "Psiquico", "Agua", "Agua", 
            "Electrico", "Electrico", "Planta/Psiquico", "Planta/Psiquico", "Tierra", "Tierra", "Lucha", "Lucha",
            "Normal", "Veneno", "Veneno", "Tierra/Roca", "Tierra/Roca", "Normal", "Planta", "Normal", "Agua", "Agua",
            "Agua", "Agua", "Agua", "Agua/Psiquico", "Psiquico/Hada", "Bicho/Volador", "Hielo/Psiquico", "Electrico",
            "Fuego", "Bicho", "Normal", "Agua", "Agua/Volador", "Agua/Hielo", "Normal", "Normal", "Agua", "Electrico",
            "Fuego", "Normal", "Roca/Agua", "Roca/Agua", "Roca/Agua", "Roca/Agua", "Roca/Volador", "Normal", "Hielo/Volador",
            "Electrico/Volador", "Fuego/Volador", "Dragon", "Dragon", "Dragon/Volador", "Psiquico", "Psiquico"
        ]
    },
    2: {
        nombres: [
            "Chikorita", "Bayleef", "Meganium", "Cyndaquil", "Quilava", "Typhlosion", 
            "Totodile", "Croconaw", "Feraligatr", "Sentret", "Furret", "Hoothoot", "Noctowl", "Ledyba", "Ledian", 
            "Spinarak", "Ariados", "Crobat", "Chinchou", "Lanturn", "Pichu", "Cleffa", "Igglybuff", "Togepi", 
            "Togetic", "Natu", "Xatu", "Mareep", "Flaaffy", "Ampharos", "Bellossom", "Marill", "Azumarill", 
            "Sudowoodo", "Politoed", "Hoppip", "Skiploom", "Jumpluff", "Aipom", "Sunkern", "Sunflora", "Yanma", 
            "Wooper", "Quagsire", "Espeon", "Umbreon", "Murkrow", "Slowking",  
            "Misdreavus", "Unown", "Wobbuffet", "Girafarig", "Pineco", "Forretress", "Dunsparce", "Gligar", "Steelix",
            "Snubbull", "Granbull", "Qwilfish", "Scizor", "Shuckle", "Heracross", "Sneasel", 
            "Teddiursa", "Ursaring", "Slugma", "Magcargo", "Swinub", "Piloswine", "Corsola", 
            "Remoraid", "Octillery", "Delibird", "Mantine", "Skarmory", "Houndour", "Houndoom", 
            "Kingdra", "Phanpy", "Donphan", "Porygon2", "Stantler", "Smeargle", "Tyrogue", "Hitmontop", "Smoochum", 
            "Elekid", "Magby", "Miltank", "Blissey", "Raikou", "Entei", "Suicune", "Larvitar", "Pupitar", "Tyranitar", 
            "Lugia", "Ho-Oh", "Celebi"
        ],
        tipos: [
            "Planta", "Planta", "Planta", "Fuego", "Fuego", "Fuego", 
            "Agua", "Agua", "Agua", "Normal", "Normal", "Normal/Volador", "Normal/Volador", "Bicho/Volador", 
            "Bicho/Volador", "Bicho/Veneno", "Bicho/Veneno", "Veneno/Volador", "Agua/Electrico", 
            "Agua/Electrico", "Electrico", "Hada", "Normal/Hada", "Hada", "Hada/Volador", "Psiquico/Volador", 
            "Psiquico/Volador", "Electrico", "Electrico", "Electrico", "Planta", "Agua/Hada", "Agua/Hada", 
            "Roca", "Agua", "Planta/Volador", "Planta/Volador", "Planta/Volador", "Normal", "Planta", "Planta",
            "Bicho/Volador", "Agua/Tierra", "Agua/Tierra", "Psiquico", "Siniestro", "Siniestro/Volador", 
            "Agua/Psiquico", "Fantasma", "Psiquico", "Psiquico", "Normal/Psiquico", "Bicho", "Bicho/Acero",
            "Normal", "Tierra/Volador", "Acero/Tierra", "Hada", "Hada", "Agua/Veneno", "Bicho/Acero",
            "Bicho/Roca", "Bicho/Lucha", "Siniestro/Hielo", "Normal", "Normal", "Fuego", "Fuego/Roca",
            "Hielo/Tierra", "Hielo/Tierra", "Agua/Roca", "Agua", "Agua", "Hielo/Volador",
            "Agua/Volador", "Volador/Acero", "Siniestro/Fuego", "Siniestro/Fuego", "Agua/Dragon", "Tierra", "Tierra", 
            "Normal", "Normal", "Normal", "Lucha", "Lucha", "Hielo/Psiquico", "Electrico", "Fuego",
            "Normal", "Normal", "Electrico", "Fuego", "Agua", "Roca/Tierra", "Roca/Tierra", "Roca/Siniestro",
            "Psiquico/Volador", "Fuego/Volador", "Psiquico/Planta"
        ]    
    },
    3: {
        nombres: [
            "Treecko", "Grovyle", "Sceptile", "Torchic", "Combusken", "Blaziken", "Mudkip", 
            "Marshtomp", "Swampert", "Poochyena", "Mightyena", "Zigzagoon", "Linoone", 
            "Wurmple", "Silcoon", "Beautifly", "Cascoon", "Dustox", "Lotad", "Lombre", "Ludicolo", "Seedot", "Nuzleaf", 
            "Shiftry", "Taillow", "Swellow", "Wingull", "Pelipper", "Ralts", "Kirlia", "Gardevoir", "Surskit", "Masquerain", 
            "Shroomish", "Breloom", "Slakoth", "Vigoroth", "Slaking", "Nincada", "Ninjask", "Shedinja", "Whismur", "Loudred", 
            "Exploud", "Makuhita", "Hariyama", "Azurill", "Nosepass", "Skitty", "Delcatty", "Sableye", "Mawile", "Aron", 
            "Lairon", "Aggron", "Meditite", "Medicham", "Electrike", "Manectric", "Plusle", "Minun", "Volbeat", "Illumise", 
            "Roselia", "Gulpin", "Swalot", "Carvanha", "Sharpedo", "Wailmer", "Wailord", "Numel", "Camerupt", "Torkoal", 
            "Spoink", "Grumpig", "Spinda", "Trapinch", "Vibrava", "Flygon", "Cacnea", "Cacturne", "Swablu", "Altaria", 
            "Zangoose", "Seviper", "Lunatone", "Solrock", "Barboach", "Whiscash", "Corphish", "Crawdaunt", "Baltoy", 
            "Claydol", "Lileep", "Cradily", "Anorith", "Armaldo", "Feebas", "Milotic", "Castform", "Kecleon", "Shuppet", 
            "Banette", "Duskull", "Dusclops", "Tropius", "Chimecho", "Absol", "Wynaut", "Snorunt", "Glalie", "Spheal", 
            "Sealeo", "Walrein", "Clamperl", "Huntail", "Gorebyss", "Relicanth", "Luvdisc", "Bagon", "Shelgon", "Salamence", 
            "Beldum", "Metang", "Metagross", "Regirock", "Regice", "Registeel", "Latias", "Latios", "Kyogre", "Groudon", 
            "Rayquaza", "Jirachi", "Deoxys"
        ],
        tipos: [
            "Planta", "Planta", "Planta", "Fuego", "Fuego/Lucha", "Fuego/Lucha", 
            "Agua", "Agua/Tierra", "Agua/Tierra","Siniestro", "Siniestro", "Normal", 
            "Normal", "Bicho", "Bicho", "Bicho/Volador", "Bicho", "Bicho/Veneno", 
            "Agua/Planta", "Agua/Planta", "Agua/Planta", "Planta", "Planta/Siniestro", 
            "Planta/Siniestro", "Normal/Volador", "Normal/Volador", "Agua/Volador", 
            "Agua/Volador", "Psiquico/Hada", "Psiquico/Hada", "Psiquico/Hada", 
            "Bicho/Agua", "Bicho/Volador", "Planta", "Planta/Lucha", "Normal", 
            "Normal", "Normal", "Bicho/Tierra", "Bicho/Volador", "Bicho/Fantasma", 
            "Normal", "Normal", "Normal", "Lucha", "Lucha", "Normal/Hada", "Roca", 
            "Normal", "Normal", "Siniestro/Fantasma", "Acero/Hada", "Acero/Roca", 
            "Acero/Roca", "Acero/Roca", "Lucha/Psiquico", "Lucha/Psiquico", 
            "Electrico", "Electrico", "Electrico", "Electrico", "Bicho", "Bicho", 
            "Planta/Veneno", "Veneno", "Veneno", "Agua/Siniestro", "Agua/Siniestro", 
            "Agua", "Agua", "Fuego/Tierra", "Fuego/Tierra", "Fuego", "Psiquico", 
            "Psiquico", "Normal", "Tierra", "Tierra/Dragon", "Tierra/Dragon", 
            "Planta", "Planta/Siniestro", "Normal/Volador", "Dragon/Volador", 
            "Normal", "Veneno", "Roca/Psiquico", "Roca/Psiquico", "Agua/Tierra", 
            "Agua/Tierra", "Agua", "Agua/Siniestro", "Tierra/Psiquico", "Tierra/Psiquico", 
            "Roca/Planta", "Roca/Planta", "Roca/Bicho", "Roca/Bicho", "Agua", "Agua", 
            "Normal", "Normal", "Fantasma", "Fantasma", "Fantasma", "Fantasma", 
            "Planta/Volador", "Psiquico", "Siniestro", "Psiquico", "Hielo", 
            "Hielo", "Hielo/Agua", "Hielo/Agua", "Hielo/Agua", "Agua", "Agua", 
            "Agua", "Agua/Roca", "Agua", "Dragon", "Dragon", "Dragon/Volador", 
            "Acero/Psiquico", "Acero/Psiquico", "Acero/Psiquico", "Roca", 
            "Hielo", "Acero", "Dragon/Psiquico", "Dragon/Psiquico", "Agua", 
            "Tierra", "Dragon/Volador", "Acero/Psiquico", "Psiquico"
        ]
    },
    4: {
        nombres: [
            "Turtwig", "Grotle", "Torterra", "Chimchar", "Monferno", "Infernape", 
            "Piplup", "Prinplup", "Empoleon", "Starly", "Staravia", "Staraptor", 
            "Bidoof", "Bibarel", "Kricketot", "Kricketune", "Shinx", "Luxio", 
            "Luxray", "Budew", "Roserade", "Cranidos", "Rampardos", "Shieldon", 
            "Bastiodon", "Burmy", "Wormadam", "Mothim", "Combee", "Vespiqueen", 
            "Pachirisu", "Buizel", "Floatzel", "Cherubi", "Cherrim", "Shellos", 
            "Gastrodon", "Ambipom", "Drifloon", "Drifblim", "Buneary", "Lopunny", 
            "Mismagius", "Honchokrow", "Glameow", "Purugly", "Chingling", "Stunky", 
            "Skuntank", "Bronzor", "Bronzong", "Bonsly", "Mime Jr", "Happiny", 
            "Chatot", "Spiritomb", "Gible", "Gabite", "Garchomp", "Munchlax", 
            "Riolu", "Lucario", "Hippopotas", "Hippowdon", "Skorupi", "Drapion", 
            "Croagunk", "Toxicroak", "Carvinine", "Finneon", "Lumineon", "Mantyke", 
            "Snover", "Abomasnow", "Weavile", "Magnezone", "Lickilicky", "Rhyperior", 
            "Tangrowth", "Electivire", "Magmortar", "Togekiss", "Yanmega", "Leafeon", 
            "Glaceon", "Gliscor", "Mamoswine", "Porygon-Z", "Gallade", "Probopass", 
            "Dusknoir", "Frosslas", "Rotom", "Uxie", "Mesprit", "Azelf", "Dialga", 
            "Palkia", "Heatran", "Regigigas", "Giratina", "Cresselia", "Phione", 
            "Manaphy", "Darkrai", "Shaymin", "Arceus"
        ],
        tipos: [
            "Planta", "Planta", "Planta/Tierra", "Fuego", "Fuego/Lucha", "Fuego/Lucha", 
        "Agua", "Agua", "Agua/Acero", "Normal/Volador", "Normal/Volador", "Normal/Volador", 
        "Normal", "Normal/Agua", "Bicho", "Bicho", "Electrico", "Electrico", "Electrico", 
        "Planta/Veneno", "Planta/Veneno", "Roca", "Roca", "Roca/Acero", "Roca/Acero", 
        "Bicho","Bicho/Planta", "Bicho/Volador", "Bicho/Volador", "Bicho/Volador", 
        "Electrico", "Agua","Agua", "Planta", "Planta", "Agua", "Agua/Tierra", 
        "Normal", "Fantasma/Volador", "Fantasma/Volador", "Normal", "Normal", 
        "Fantasma", "Fantasma/Volador", "Normal", "Normal", "Psiquico", "Veneno/Siniestro", 
        "Veneno/Siniestro", "Acero/Psiquico", "Acero/Psiquico", "Roca", "Psiquico/Hada", 
        "Normal", "Normal/Volador", "Fantasma/Siniestro", "Dragon/Tierra", "Dragon/Tierra", 
        "Dragon/Tierra", "Normal", "Lucha", "Lucha/Acero", "Tierra", "Tierra", 
        "Veneno/Bicho", "Veneno/Siniestro", "Veneno/Lucha", "Veneno/Lucha", "Planta", 
        "Agua", "Agua", "Agua/Volador", "Planta/Hielo", "Planta/Hielo", "Siniestro/Hielo", 
        "Electrico/Acero", "Normal", "Tierra/Roca", "Planta", "Electrico", "Fuego", 
        "Hada/Volador", "Bicho/Volador", "Planta", "Hielo", "Tierra/Volador", "Hielo/Tierra", 
        "Normal", "Psiquico/Lucha", "Roca/Acero", "Fantasma", "Hielo/Fantasma", "Electrico/Fantasma", 
        "Psiquico", "Psiquico", "Psiquico", "Acero/Dragon", "Agua/Dragon", "Fuego/Acero", "Normal", 
        "Fantasma/Dragon", "Psiquico", "Agua", "Agua", "Siniestro", "Planta", "Normal"
        ]
    },
    5: {
        nombres: [
            "Victini", "Snivy", "Servine", "Serperior", "Tepig", "Pignite", "Emboar", 
        "Oshawott", "Dewott", "Samurott", "Patrat", "Watchog", "Lillipup", "Herdier", 
        "Stoutland", "Purrloin", "Liepard", "Pansage", "Simisage", "Pansear", "Simiesar", 
        "Panpour", "Simipour", "Munna", "Musharna", "Pidove", "Tranquill", "Unfezant", 
        "Blitzle", "Zebstrika", "Roggenrola", "Boldore", "Gigalith", "Woobat", "Swoobat", 
        "Drillbur", "Excadrill", "Audino", "Timburr", "Gurdurr", "Conkeldurr", "Tympole", 
        "Palpitoad", "Seismitoad", "Throh", "Sawk", "Sewaddle", "Swadloon", "Leavanny", 
        "Venipede", "Whirlipede", "Scolipede", "Cottonee", "Whimsicott", "Petilil", "Lilligant", 
        "Basculin", "Sandile", "Krokorok", "Krookodile", "Darumaka", "Darmanitan", "Maractus", 
        "Dwebble", "Crustle", "Scraggy", "Scrafty", "Sigilyph", "Yamask", "Cofragrigus", 
        "Tirtouga", "Carracosta", "Archen", "Archeops", "Trubissh", "Garbodor", "Zorua", "Zoroak", 
        "Minccino", "Cincinno", "Gothita", "Gothorita", "Gothitelle", "Solosis", "Duosion", 
        "Reuniclus", "Ducklett", "Swanna", "Vanillite", "Vanillish", "Vanilluxe", "Deerling", 
        "Sawsbuck", "Emolga", "Karrablast", "Escavalier", "Foongus", "Amoonguss", "Frillish", 
        "Jellicent", "Alomomola", "Joltik", "Galvantula", "Ferroseed", "Ferrothorn", "Klink", 
        "Klang", "Klinklang", "Tynamo", "Eelektrik", "Eelektross", "Elgyem", "Beheeyem", "Litwick", 
        "Lampent", "Chandelure", "Axew", "Fraxure", "Haxorus", "Cubchoo", "Beartic", "Cryogonal", 
        "Shelmet", "Accelgor", "Stunkfish", "Mienfoo", "Mienshao", "Druddigon", "Golett", "Golurk", 
        "Pawniard", "Bisharp", "Boufallant", "Rufflet", "Braviary", "Vullaby", "Mandibuzz", "Heatmor", 
        "Durant", "Deino", "Zwelious", "Hydreigon", "Larvesta", "Volcarona", "Cobalion", "Terrakion", 
        "Virizion", "Tornadus", "Thundurus", "Reshiram", "Zekrom", "Landorus", "Kyurem", "Keldeo", 
        "Meloetta", "Genesect"
        ],
        tipos: [
            "Psiquico/Fuego", "Planta", "Planta", "Planta", "Fuego", "Fuego/Lucha", "Fuego/Lucha", 
        "Agua", "Agua", "Agua", "Normal", "Normal", "Normal", "Normal", "Normal", 
        "Siniestro", "Siniestro", "Planta", "Planta", "Fuego", "Fuego", "Agua", "Agua", 
        "Psiquico", "Psiquico", "Normal/Volador", "Normal/Volador", "Normal/Volador", 
        "Electrico", "Electrico", "Roca", "Roca", "Roca", "Psiquico/Volador", "Psiquico/Volador", 
        "Tierra", "Tierra/Acero", "Normal", "Lucha", "Lucha", "Lucha", "Agua", "Agua/Tierra", 
        "Agua/Tierra", "Lucha", "Lucha", "Bicho/Planta", "Bicho/Planta", "Bicho/Planta", 
        "Bicho/Veneno", "Bicho/Veneno", "Bicho/Veneno", "Planta/Hada", "Planta/Hada", 
        "Planta", "Planta", "Agua", "Tierra/Siniestro", "Tierra/Siniestro", "Tierra/Siniestro", 
        "Fuego", "Fuego", "Planta", "Bicho/Roca", "Bicho/Roca", "Siniestro/Lucha", 
        "Siniestro/Lucha", "Psiquico/Volador", "Fantasma", "Fantasma", "Agua/Roca", 
        "Agua/Roca", "Roca/Volador", "Roca/Volador", "Veneno", "Veneno", "Siniestro", 
        "Siniestro", "Normal", "Normal", "Psiquico", "Psiquico", "Psiquico", "Psiquico", 
        "Psiquico", "Psiquico", "Agua/Volador", "Agua/Volador", "Hielo", "Hielo", "Hielo", 
        "Normal/Planta", "Normal/Planta", "Electrico/Volador", "Bicho", "Bicho/Acero", 
        "Planta/Veneno", "Planta/Veneno", "Agua/Fantasma", "Agua/Fantasma", "Agua", 
        "Bicho/Electrico", "Bicho/Electrico", "Planta/Acero", "Planta/Acero", "Acero", 
        "Acero", "Acero", "Electrico", "Electrico", "Electrico", "Psiquico", "Psiquico", 
        "Fantasma/Fuego", "Fantasma/Fuego", "Fantasma/Fuego", "Dragon", "Dragon", "Dragon", 
        "Hielo", "Hielo", "Hielo", "Bicho", "Bicho", "Tierra/Electrico", "Lucha", "Lucha", 
        "Dragon", "Tierra/Fantasma", "Tierra/Fantasma", "Siniestro/Acero", "Siniestro/Acero", 
        "Normal", "Normal/Volador", "Normal/Volador", "Siniestro/Volador", "Siniestro/Volador", 
        "Fuego", "Bicho/Acero", "Siniestro/Dragon", "Siniestro/Dragon", "Siniestro/Dragon", 
        "Bicho/Fuego", "Bicho/Fuego", "Acero/Lucha", "Roca/Lucha", "Planta/Lucha", 
        "Volador", "Electrico/Volador", "Dragon/Fuego", "Dragon/Electrico", "Tierra/Volador", 
        "Dragon/Hielo", "Agua/Lucha", "Normal/Psiquico", "Bicho/Acero"
        ]
    },
    6: {
        nombres: [
            "Chespin", "Quilladin", "Chesnaught", "Fennekin", "Braixen", "Delphox", 
            "Froakie", "Frogadier", "Greninja", "Bunnelby", "Diggersby", 
            "Fletchling", "Fletchinder", "Talonflame", "Scatterbug", "Spewpa", 
            "Vivillon", "Litleo", "Pyroar", "Flabébé", "Floette", 
            "Florges", "Skiddo", "Gogoat", "Pancham", "Pangoro", "Furfrou", 
            "Espurr", "Meowstic", "Honedge", "Doublade", "Aegislash", 
            "Spritzee", "Aromatisse", "Swirlix", "Slurpuff", "Inkay", "Malamar", 
            "Binacle", "Barbaracle", "Skrelp", "Dragalge", "Clauncher", 
            "Clawitzer", "Helioptile", "Heliolisk", "Tyrunt", "Tyrantrum", "Amaura", 
            "Aurorus", "Sylveon", "Hawlucha", "Dedenne", "Carbink", 
            "Goomy", "Sliggoo", "Goodra", "Klefki", "Phantump", "Trevenant", 
            "Pumpkaboo", "Gourgeist", "Bergmite", "Avalugg", "Noibat", "Noivern", 
            "Xerneas", "Yveltal", "Zygarde", "Diancie", "Hoopa", "Volcanion"
        ],
        tipos: [
            "Planta", "Planta", "Planta/Lucha", "Fuego", "Fuego", "Fuego/Psiquico", 
            "Agua", "Agua", "Agua/Siniestro", "Normal/Volador", "Normal/Volador", "Normal/Volador", 
            "Bicho", "Bicho", "Bicho/Volador", "Fuego/Volador", "Fuego/Volador", "Fuego/Volador", 
            "Hada", "Hada", "Planta", "Planta", "Lucha", "Lucha", "Hada", "Hada", 
            "Psiquico", "Psiquico", "Hada", "Hada", "Acero/Hada", "Acero/Hada", 
            "Siniestro/Psiquico", "Siniestro/Psiquico", "Veneno/Dragón", "Veneno/Dragón", 
            "Agua/Dragón", "Agua/Dragón", "Roca/Dragón", "Roca/Dragón", "Roca/Hielo", "Roca/Hielo", 
            "Hada", "Lucha/Volador", "Electrico/Hada", "Dragón", "Dragón", "Dragón", 
            "Acero/Fantasma", "Acero/Fantasma", "Acero/Fantasma", "Acero/Fantasma", 
            "Hada", "Hada", "Siniestro/Volador", "Planta/Fantasma", "Planta/Fantasma", 
            "Fantasma/Planta", "Fantasma/Planta", "Hielo", "Hielo", "Dragón/Tierra", 
            "Hada", "Siniestro/Fuego", "Siniestro/Fuego", "Siniestro/Hada", "Sinisetro/Volador", 
            "Hada", "Dragón/Tierra", "Roca/Hada", "Psiquico/Fantasma", "Fuego/Agua"

        ]
    },
    7: {
        nombres: [
            "Rowlet", "Dartrix", "Decidueye", "Litten", "Torracat", "Incineroar", "Popplio", "Brionne", "Primarina", "Pikipek", 
            "Trumbeak", "Toucannon", "Yungoos", "Gumshoos", "Grubbin", "Charjabug", "Vikavolt", "Crabrawler", "Crabominable", "Oricorio", "Cutiefly", 
            "Ribombee", "Rockruff", "Lycanroc", "Wishiwashi", "Mareanie", "Toxapex", "Mudbray", "Mudsdale", "Dewpider", "Araquanid", "Fomantis", 
            "Lurantis", "Morelull", "Shiinotic", "Salandit", "Salazzle", "Stufful", "Bewear", "Bounsweet", "Steenee", "Tsareena", "Comfey", "Oranguru",
            "Passimian", "Wimpod", "Golisopod", "Sandygast", "Palossand", "Pyukumuku", "Código Cero", "Silvally", "Minior", "Komala", "Turtonator", 
            "Togedemaru", "Mimikyu", "Bruxish", "Drampa", "Dhelmise", "Jangmo-o", "Hakamo-o", "Kommo-o", "Tapu Koko", "Tapu Lele", "Tapu Bulu", "Tapu Fini",
            "Cosmog", "Cosmoem", "Solgaleo", "Lunala", "Nihilego", "Buzzwole", "Pheromosa", "Xurkitree", "Celesteela", "Kartana", "Guzzlord", "Necrozma",
            "Magearna", "Marshadow", "Poipole", "Naganadel", "Stakataka", "Blacephalon", "Zeraora", "Meltan", "Melmetal"

        ],
        tipos: [
            "Planta/Volador", "Planta/Volador", "Planta/Fantasma", "Fuego", "Fuego", "Fuego/Siniestro",
            "Agua", "Agua", "Agua/Hada", "Normal/Volador", "Normal/Volador", "Normal/Volador", 
            "Normal", "Normal", "Bicho", "Bicho/Electrico", "Bicho/Electrico", "Lucha", "Lucha/Hielo",
            "Volador/Fuego/Electrico/Psiquico/Fantasma", "Bicho/Hada", "Bicho/Hada", "Roca", "Roca", 
            "Agua", "Veneno/Agua", "Veneno/Agua", "Tierra", "Tierra", "Agua/Bicho", "Agua/Bicho", 
            "Planta", "Planta", "Planta/Hada", "Planta/Hada", "Veneno/Fuego", "Veneno/Fuego", 
            "Normal/Lucha", "Normal/Lucha", "Planta", "Planta", "Planta", "Hada", "Normal/Psiquico",
            "Lucha", "Bicho/Agua", "Bicho/Agua", "Fantasma/Tierra", "Fantasma/Tierra", "Agua", 
            "Normal", "Normal", "Roca/Volador", "Normal", "Fuego/Dragon", "Electrico/Acero", 
            "Fantasma/Hada", "Agua/Psiquico", "Normal/Dragon", "Fantasma/Planta", "Dragon", 
            "Dragon/Lucha", "Dragon/Lucha", "Electrico/Hada", "Psiquico/Hada", "Planta/Hada", 
            "Agua/Hada", "Psiquico", "Psiquico", "Psiquico/Acero", "Psiquico/Fantasma", "Roca/Fantasma",
            "Bicho/Lucha", "Bicho/Lucha", "Electrico", "Acero/Volador", "Planta/Acero", "Siniestro/Dragon", 
            "Psiquico/Acero/Fantasma/Dragon", "Acero/Hada", "Lucha/Fantasma", "Veneno", "Veneno/Dragon",
            "Roca/Acero", "Fuego/Fantasma", "Electrico", "Acero", "Acero"

        ]
    },
    8: {
        nombres: [
            "Grookey", "Thwackey", "Rillaboom", "Scorbunny", "Raboot", "Cinderace", "Sobble", "Drizzile", "Inteleon", 
            "Skwovet", "Greedent", "Rookidee", "Corvisquire", "Corviknight", "Blipbug", "Dottler", "Orbeetle", "Nickit", 
            "Thievul", "Gossifleur", "Eldegoss", "Wooloo", "Dubwool", "Chewtle", "Drednaw","Yamper", "Boltund", "Rolycoly", 
            "Carkol", "Coalossal", "Applin", "Flapple", "Appletun", "Silicobra", "Sandaconda", "Cramorant", "Arrokuda",
            "Barraskewda", "Toxel", "Toxtricity", "Sizzlipede", "Centiskorch", "Clobbopus", "Grapploct", "Sinistea", "Polteageist", 
            "Hatenna", "Hattrem", "Hatterene", "Impidimp", "Morgrem", "Grimmsnarl", "Obstagoon", "Perrserker", "Cursola", "Sirfetch’d", 
            "Mr. Rime", "Runerigus", "Milcery", "Alcremie", "Falinks", "Pincurchin", "Snom", "Frosmoth", "Stonjourner", "Eiscue", 
            "Indeedee", "Morpeko", "Cufant", "Copperajah", "Dracozolt","Arctozolt", "Dracovish", "Arctovish", "Duraludon", "Dreepy", 
            "Drakloak", "Dragapult", "Zacian", "Zamazenta", "Eternatus", "Kubfu", "Urshifu", "Zarude", "Regieleki", "Regidrago", 
            "Glastrier", "Spectrier", "Calyrex", "Wyrdeer", "Kleavor", "Ursaluna", "Basculegion", "Sneasler", "Overqwil", "Enamorus"

        ],
        tipos: [
            "Planta", "Planta", "Planta", "Fuego", "Fuego", "Fuego", "Agua", "Agua", "Agua", 
            "Normal", "Normal", "Volador", "Volador", "Volador/Acero", "Bicho", "Bicho/Psiquico",
            "Bicho/Psiquico", "Siniestro", "Siniestro", "Planta", "Planta", "Normal", "Normal",
            "Agua", "Agua/Roca", "Electrico", "Electrico", "Roca", "Roca/Fuego", "Roca/Fuego",
            "Planta/Dragon", "Planta/Dragon", "Planta/Dragon", "Tierra", "Tierra", "Volador/Agua",
            "Agua", "Agua", "Electrico/Veneno", "Electrico/Veneno", "Fuego/Bicho", "Fuego/Bicho",
            "Lucha", "Lucha", "Fantasma", "Fantasma", "Psiquico", "Psiquico", "Psiquico/Hada", 
            "Siniestro/Hada", "Siniestro/Hada", "Siniestro/Hada", "Siniestro/Normal", "Acero",
            "Fantasma", "Lucha", "Hielo/Psiquico", "Tierra/Fantasma", "Hada", "Hada", "Lucha", 
            "Electrico", "Hielo/Bicho", "Hielo/Bicho", "Roca", "Hielo", "Psiquico/Normal",
            "Electrico/Siniestro", "Acero", "Acero", "Electrico/Dragon", "Electrico/Hielo",
            "Agua/Dragon", "Agua/Hielo", "Acero/Dragon", "Dragon/Fantasma", "Dragon/Fantasma",
            "Dragon/Fantasma", "Hada/Acero", "Lucha/Acero", "Veneno/Dragon", "Lucha", 
            "Lucha/Siniestro/Agua", "Siniestro/Planta", "Electrico", "Dragon", "Hielo", "Fantasma",
            "Psiquico/Planta/Hielo/Fantasma", "Normal/Psiquico", "Bicho/Roca", "Tierra/Normal",
            "Agua/Fantasma", "Lucha/Veneno", "Siniestro/Veneno", "Hada/Volador"

        ]
    },
    9: {
        nombres: [
            "Sprigatito", "Floragato", "Meowscarada", "Fuecoco", "Crocalor", "Skeledirge", "Quaxly", "Quaxwell", "Quaquaval", "Lechonk", 
            "Oinkologne", "Tarountula", "Spidops", "Nymble", "Lokix", "Pawmi", "Pawmo", "Pawmot", "Tandemaus", "Maushold", "Fidough", "Dachsbun", "Smoliv",
            "Dolliv", "Arboliva", "Squawkabilly", "Nacli", "Naclstack", "Garganacl", "Charcadet", "Armarouge", "Ceruledge", "Tadbulb", "Bellibolt", 
            "Wattrel", "Kilowattrel", "Maschiff", "Mabosstiff", "Shroodle", "Grafaiai", "Bramblin", "Brambleghast", "Toedscool", "Toedscruel", "Klawf",
            "Capsakid", "Scovillain", "Rellor", "Rabsca", "Flittle", "Espathra", "Tinkatink", "Tinkatuff", "Tinkaton", "Wiglett", "Wugtrio", "Bombirdier",
            "Finizen", "Palafin", "Varoom", "Revavroom", "Cyclizar", "Orthworm", "Glimmet", "Glimmora", "Greavard", "Houndstone", "Flamigo", "Cetoddle",
            "Cetitan", "Veluza", "Dondozo", "Tatsugiri", "Annihilape", "Clodsire", "Farigiraf", "Dudunsparce", "Kingambit", "Colmilargo", "Colagrito", 
            "Furioseta", "Melenaleteo", "Reptalada", "Pelarena", "Ferrodada", "Ferrosaco", "Ferropalmas", "Ferrocuello", "Ferropolilla", "Ferropúas", 
            "Frigibax", "Arctibax", "Baxcalibur", "Gimmighoul", "Gholdengo", "Wo-Chien", "Chien-Pao", "Ting-Lu", "Chi-Yu", "Bramaluna", "Ferropaladín", 
            "Koraidon", "Miraidon", "Ondulagua", "Ferroverdor", "Dipplin", "Poltchageist", "Sinistcha", "Okidogi", "Munkidori", "Fezandipiti", "Ogerpon", 
            "Archaludon", "Hydrapple", "Flamariete", "Electrofuria", "Ferromole", "Ferrotesta", "Terapagos", "Pecharunt"
        ],
        tipos: [
            "Planta", "Planta", "Planta/Siniestro", "Fuego", "Fuego", "Fuego/Fantasma", 
            "Agua", "Agua", "Agua/Lucha", "Normal", "Normal", "Bicho", "Bicho", 
            "Bicho/Siniestro", "Normal/Volador", "Normal/Volador", "Electrico", 
            "Electrico", "Electrico", "Agua/Tierra", "Agua/Tierra", "Hada", 
            "Hada", "Hada", "Lucha", "Lucha/Siniestro", "Roca", "Roca", 
            "Psiquico", "Psiquico", "Fuego/Psiquico", "Fuego/Fantasma", "Agua", 
            "Agua/Psiquico", "Electrico", "Electrico", "Normal/Planta", "Normal/Planta", 
            "Siniestro", "Siniestro", "Normal/Hada", "Normal/Hada", "Fantasma", 
            "Fantasma", "Fantasma", "Fantasma", "Hada", "Hada", "Planta/Fuego", 
            "Tierra", "Acero", "Acero", "Agua/Lucha", "Agua/Fuego", "Electrico", 
            "Electrico", "Normal", "Normal", "Tierra", "Tierra/Lucha", "Hielo", 
            "Hielo", "Hielo", "Hielo/Dragon", "Roca", "Roca", "Agua", "Agua/Psiquico", 
            "Veneno/Normal", "Veneno/Normal", "Siniestro/Planta", "Siniestro/Planta", 
            "Tierra/Veneno", "Agua", "Siniestro/Agua", "Acero/Fantasma", "Roca/Veneno", 
            "Dragon/Hielo", "Siniestro/Fuego", "Siniestro/Tierra", "Siniestro/Hielo", 
            "Siniestro/Dragon", "Tierra/Lucha", "Tierra/Volador", "Siniestro/Planta", 
            "Tierra/Lucha", "Psiquico/Hada", "Planta/Lucha", "Fantasma/Hada", "Agua/Lucha", 
            "Veneno/Volador", "Siniestro/Dragon", "Hada/Lucha", "Electrico/Agua", "Fuego/Acero", 
            "Dragon/Hielo", "Acero/Dragon", "Fuego/Dragon", "Electrico/Dragon", "Psiquico/Dragon", 
            "Lucha/Dragon", "Normal/Dragon", "Planta/Fantasma", "Siniestro/Veneno", "Agua/Dragon", 
            "Planta/Hada", "Fuego/Hada", "Agua/Hada", "Psiquico/Dragon", "Veneno/Cadena", 
            "Acero/Dragon", "Fuego/Dragon", "Roca/Dragon", "Electrico/Dragon", "Psiquico/Dragon", 
            "Hielo/Dragon", "Hada/Dragon", "Normal", "Planta/Veneno", "Bicho/Lucha"
        ]
    },
    10: {
        nombres: [
            "Browt", "Pombon", "Gecqua"
        ],
        tipos: [
            "Planta", "Fuego", "Agua"
        ]
    }
};